// Auto-generated by Supabase CLI — run `npx supabase gen types typescript` to update
// Do not edit manually

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          role: "client" | "specialist"
          phone: string | null
          created_at: string
        }
        Insert: Omit<Database["public"]["Tables"]["profiles"]["Row"], "created_at">
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>
      }
      services: {
        Row: {
          id: string
          name: string
          description: string | null
          duration_minutes: number
          price: number
          image_url: string | null
          created_at: string
        }
        Insert: Omit<Database["public"]["Tables"]["services"]["Row"], "id" | "created_at">
        Update: Partial<Database["public"]["Tables"]["services"]["Insert"]>
      }
      appointments: {
        Row: {
          id: string
          client_id: string
          service_id: string
          date: string
          status: "pending" | "confirmed" | "cancelled" | "completed"
          reason: string | null
          symptoms: string | null
          stripe_payment_intent_id: string | null
          created_at: string
        }
        Insert: Omit<Database["public"]["Tables"]["appointments"]["Row"], "id" | "created_at">
        Update: Partial<Database["public"]["Tables"]["appointments"]["Insert"]>
      }
      reviews: {
        Row: {
          id: string
          appointment_id: string
          client_id: string
          service_id: string
          rating: number
          comment: string | null
          approved: boolean
          created_at: string
        }
        Insert: Omit<Database["public"]["Tables"]["reviews"]["Row"], "id" | "created_at">
        Update: Partial<Database["public"]["Tables"]["reviews"]["Insert"]>
      }
      products: {
        Row: {
          id: string
          name: string
          description: string | null
          price: number
          stock: number
          image_url: string | null
          dimensions: string | null
          medium: string | null
          created_at: string
        }
        Insert: Omit<Database["public"]["Tables"]["products"]["Row"], "id" | "created_at">
        Update: Partial<Database["public"]["Tables"]["products"]["Insert"]>
      }
      orders: {
        Row: {
          id: string
          client_id: string
          total: number
          status: "pending" | "paid" | "shipped" | "delivered" | "refunded"
          stripe_payment_intent_id: string | null
          created_at: string
        }
        Insert: Omit<Database["public"]["Tables"]["orders"]["Row"], "id" | "created_at">
        Update: Partial<Database["public"]["Tables"]["orders"]["Insert"]>
      }
    }
  }
}
